name: Fix

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run check
      - run: pnpm run lint:fix
      - run: pnpm run test:ci
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      - run: git commit -a -m "Fix lint automatically"
      - run: git push origin
