name: Release

on:
  push:
    branches:
      - production
      - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_VARIANT: ${{github.ref_name}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run test:ci
      - name: Get Last Version Bump
        uses: ./.github/actions/getLastVersionBump
        id: version
      - name: Update
        if: ${{ false }}
        # if: ${{  (steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas update --non-interactive --auto --channel ${{github.ref_name}} --platform android
      - name: Build
        if: ${{ false }}
        # if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas build --non-interactive --profile ${{github.ref_name}} --platform android
      - if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') }}
        id: getBuildUrl
        uses: ./.github/actions/getBuildUrl
        with:
          platform: android
          profile: ${{github.ref_name}}
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      - if: github.ref_name == 'production'
        run: pnpm changeset tag
      - if: github.ref_name == 'production'
        run: git push origin --follow-tags
      - if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') && github.ref_name == 'production' }}
        run: curl http://expo.dev/artifacts/eas/9fWqU2aSJzPev1T2xkKpZx.apk -o /tmp/application-android.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') && github.ref_name == 'production' }}
        with:
          files: /tmp/application-android.apk
