name: Release

on:
  push:
    branches:
      - production
      - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_VARIANT: ${{github.ref_name}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run check
      - run: pnpm run lint
      - run: pnpm run test:ci
      - name: Get Last Version Bump
        uses: ./.github/actions/getLastVersionBump
        id: version
      - name: Update
        if: ${{  (steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas update --non-interactive --auto --channel ${{github.ref_name}} --platform android
      - name: Build
        if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas build --non-interactive --profile ${{github.ref_name}} --platform android
      - if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') }}
        id: getBuildUrl
        uses: ./.github/actions/getBuildUrl
        with:
          platform: android
          profile: ${{github.ref_name}}
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      - if: github.ref_name == 'production'
        run: pnpm changeset tag
      - if: github.ref_name == 'production'
        run: git push origin --tags
      - if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') && github.ref_name == 'production' }}
        run: curl ${{ steps.getBuildUrl.outputs.buildUrl }} -L -o /tmp/application-android.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') && github.ref_name == 'production' }}
        with:
          files: /tmp/application-android.apk
          tag_name: v${{ steps.version.outputs.version }}
      - uses: ./.github/actions/getLastChangelog
        id: changelog
        if: github.ref_name == 'production'
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        if: github.ref_name == 'production'
        with:
          to: 845699845
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Actions App
            New version available: v${{ steps.version.outputs.version }}
            ${{ steps.version.outputs.lastVersionBump == 'patch' && 'The app will update automatically' || 'Download the new version to get the update' }}

            Changes:
            ${{steps.changelog.outputs.lastChangelog}}

            Download App: https://github.com/matheuspuel/actions-test/releases/latest/download/application-android.apk
      - name: Send Telegram Error Message
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: 845699845
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Actions App
            An error ocurred while running Release workflow.
            Branch: ${{ github.ref_name }}

            Open logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
