name: Release

on:
  push:
    branches:
      - production
      - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run test:ci
      - name: Get Last Version Bump
        uses: ./.github/actions/getLastVersionBump
        id: version
      - name: Update
        if: ${{  (steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas update --non-interactive --auto --channel ${{github.ref_name}} --platform android
      - name: Build
        if: ${{ !(steps.version.outputs.lastVersionBump == 'patch') }}
        run: eas build --non-interactive --profile ${{github.ref_name}} --platform android
      - run: pnpm changeset tag
        if: github.ref_name == 'production'
      - run: git push --follow-tags
        if: github.ref_name == 'production'
